sudo: false

language: python

python:
  - 3.6.0

cache: pip

env:
  global:
  - USER="ndip007"
  - EMAIL="owenhojunior@gmail.com"
  - REPO="py_project"
  - FILES="README.md py_project-build-tool-rdf.spdx py_project-build-tool-tv.spdx"
  - GH_REPO="github.com/${USER}/${REPO}.git"
  
install:
  - pip install -e git+https://github.com/ndip007/spdx-build-tool#egg=spdx-build-tool

script:
  - spdx-build $TRAVIS_BUILD_DIR
 
after_success:
  - MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
  - git clone git://${GH_REPO}
  - mv -f ${FILES} ${REPO}
  - cd ${REPO}
  - git remote
  - git config user.email ${EMAIL}
  - git config user.name ${USER}
  - git add ${FILES}
  - git commit -m ${MESSAGE}
  - git push "https://${TRAVIS_SECURE_TOKEN_NAME}@${GH_REPO}" master > /dev/null 2>&1

